// Mocks generated by Mockito 5.4.5 from annotations
// in courier_app/test/features/deliveries/presentation/bloc/delivery_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:courier_app/features/deliveries/domain/entities/delivery.dart'
    as _i2;
import 'package:courier_app/features/deliveries/domain/repositories/delivery_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDelivery_0 extends _i1.SmartFake implements _i2.Delivery {
  _FakeDelivery_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeliveryRoute_1 extends _i1.SmartFake implements _i2.DeliveryRoute {
  _FakeDeliveryRoute_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeliveryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryRepository extends _i1.Mock
    implements _i3.DeliveryRepository {
  MockDeliveryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Delivery>> getAssignedDeliveries() => (super.noSuchMethod(
        Invocation.method(
          #getAssignedDeliveries,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Delivery>>.value(<_i2.Delivery>[]),
      ) as _i4.Future<List<_i2.Delivery>>);

  @override
  _i4.Future<_i2.Delivery> getDeliveryById(String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeliveryById,
          [deliveryId],
        ),
        returnValue: _i4.Future<_i2.Delivery>.value(_FakeDelivery_0(
          this,
          Invocation.method(
            #getDeliveryById,
            [deliveryId],
          ),
        )),
      ) as _i4.Future<_i2.Delivery>);

  @override
  _i4.Future<void> acceptDelivery(String? deliveryId) => (super.noSuchMethod(
        Invocation.method(
          #acceptDelivery,
          [deliveryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDeliveryStatus(
    String? deliveryId,
    _i2.DeliveryStatus? status, {
    double? latitude,
    double? longitude,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDeliveryStatus,
          [
            deliveryId,
            status,
          ],
          {
            #latitude: latitude,
            #longitude: longitude,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completeDelivery(
    String? deliveryId,
    String? confirmationCode, {
    required double? latitude,
    required double? longitude,
    String? notes,
    String? proofOfDeliveryImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeDelivery,
          [
            deliveryId,
            confirmationCode,
          ],
          {
            #latitude: latitude,
            #longitude: longitude,
            #notes: notes,
            #proofOfDeliveryImageUrl: proofOfDeliveryImageUrl,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DeliveryRoute> getOptimizedRoute(String? deliveryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOptimizedRoute,
          [deliveryId],
        ),
        returnValue: _i4.Future<_i2.DeliveryRoute>.value(_FakeDeliveryRoute_1(
          this,
          Invocation.method(
            #getOptimizedRoute,
            [deliveryId],
          ),
        )),
      ) as _i4.Future<_i2.DeliveryRoute>);
}
